### PR TITLE
Kernel 6.2

### PR DESCRIPTION
**Pull request by ReillyBrogan**
- linux-firmware: Update to v20230210
- dracut: Add CPE
- kmod: Add CPE and rebuild for manifest
- linux-kvm: Update to v6.2

### CODE REVIEW

**Comment by ermo** [comment]
Could I persuade you to play a bit with enabling `CONFIG_FONT_TER16x32` (if it isn't already enabled)?

Then in `/etc/vconsole.conf`, add `FONT=ter-v32n` (we'll obviously need the terminus console fonts too).

This should give us a lovely, consistent and well-suited-to-localisation font setup ootb.

**Comment by ikeycode** [comment]
LGTM!

**Comment by ikeycode** [comment]
(id like to leave config tweaks separate)

**Comment by ikeycode** [comment]
Also I noticed belatedly the relno wasn't bumped... :D

**Pull request merged**
